# Generated by Django 5.2.8 on 2025-11-18 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_carrito_pedido_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('perfume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfumes.perfume')),
            ],
        ),
    ]
